<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cobot1</name>
  <version>0.1.0</version>
  <description>나만의 도련님 도시락 - M0609 로봇 제어 패키지</description>
  <maintainer email="yoon@todo.com">yoon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <!-- ROS2 core -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <!-- Doosan DSR -->
  <depend>dsr_msgs2</depend>
  <depend>DR_init</depend>

  <!-- Python 외부 라이브러리 (pip) -->
  <exec_depend>python3-firebase-admin</exec_depend>
  <exec_depend>python3-aiohttp</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>